export type CarCategory = 'Vintage' | 'Sports' | 'Luxury';

export interface CarModel {
  id: string;
  name: string;
  category: CarCategory;
  description: string;
  basePriceINR: number;
  specs: string;
  image: string;
}

export const carModels: CarModel[] = [
  // ── VINTAGE ──────────────────────────────────────────────────────────────
  {
    id: 'v1',
    name: 'Valorex Classic 1948',
    category: 'Vintage',
    description: 'A timeless roadster born from post-war elegance, featuring hand-stitched leather and a chrome-laden silhouette that defined an era.',
    basePriceINR: 4500000,
    specs: '2.4L Inline-6 · 110 HP · Manual 4-Speed',
    image: '/assets/generated/vintage-car-01.dim_800x500.png',
  },
  {
    id: 'v2',
    name: 'Aurentum Coupe 1955',
    category: 'Vintage',
    description: 'Sculpted curves and a thunderous straight-six engine made this coupe the crown jewel of mid-century motoring.',
    basePriceINR: 5200000,
    specs: '3.0L Straight-6 · 140 HP · Manual 4-Speed',
    image: '/assets/generated/vintage-car-02.dim_800x500.png',
  },
  {
    id: 'v3',
    name: 'Crestline Tourer 1962',
    category: 'Vintage',
    description: 'An open-top grand tourer with sweeping fins and a velvet-smooth ride that captured the spirit of the open road.',
    basePriceINR: 3800000,
    specs: '2.8L V6 · 125 HP · Manual 3-Speed',
    image: '/assets/generated/vintage-car-03.dim_800x500.png',
  },
  {
    id: 'v4',
    name: 'Meridian Saloon 1967',
    category: 'Vintage',
    description: 'Understated sophistication meets raw mechanical charm in this four-door saloon beloved by collectors worldwide.',
    basePriceINR: 4100000,
    specs: '3.2L V8 · 160 HP · Automatic 3-Speed',
    image: '/assets/generated/vintage-car-04.dim_800x500.png',
  },
  {
    id: 'v5',
    name: 'Solaris Roadster 1971',
    category: 'Vintage',
    description: 'A sun-drenched convertible with a muscular stance and a roar that echoes through mountain passes.',
    basePriceINR: 6000000,
    specs: '4.0L V8 · 200 HP · Manual 4-Speed',
    image: '/assets/generated/vintage-car-05.dim_800x500.png',
  },
  {
    id: 'v6',
    name: 'Grandeur Phaeton 1958',
    category: 'Vintage',
    description: 'Regal proportions and a hand-built body make this phaeton a rolling museum piece of automotive artistry.',
    basePriceINR: 7500000,
    specs: '4.5L V8 · 185 HP · Automatic 3-Speed',
    image: '/assets/generated/vintage-car-06.dim_800x500.png',
  },
  {
    id: 'v7',
    name: 'Thornfield Cabriolet 1964',
    category: 'Vintage',
    description: 'Delicate yet powerful, this cabriolet blends British-inspired styling with continental performance.',
    basePriceINR: 4800000,
    specs: '2.6L Inline-6 · 130 HP · Manual 4-Speed',
    image: '/assets/generated/vintage-car-07.dim_800x500.png',
  },
  {
    id: 'v8',
    name: 'Eclipso Berlinetta 1969',
    category: 'Vintage',
    description: 'A fastback silhouette and a high-revving engine made this berlinetta the darling of the racing circuit.',
    basePriceINR: 8200000,
    specs: '3.5L V8 · 220 HP · Manual 5-Speed',
    image: '/assets/generated/vintage-car-08.dim_800x500.png',
  },
  {
    id: 'v9',
    name: 'Vantara Landaulet 1953',
    category: 'Vintage',
    description: 'Opulent rear-compartment luxury with a folding roof section — the preferred carriage of dignitaries.',
    basePriceINR: 9500000,
    specs: '5.0L V8 · 175 HP · Automatic 3-Speed',
    image: '/assets/generated/vintage-car-09.dim_800x500.png',
  },
  {
    id: 'v10',
    name: 'Halcyon Speedster 1975',
    category: 'Vintage',
    description: 'The last of the true analogue speedsters — raw, unfiltered, and utterly captivating on every back road.',
    basePriceINR: 5600000,
    specs: '3.8L V8 · 240 HP · Manual 5-Speed',
    image: '/assets/generated/vintage-car-10.dim_800x500.png',
  },

  // ── SPORTS ───────────────────────────────────────────────────────────────
  {
    id: 's1',
    name: 'Phantom Eclipse GT-9',
    category: 'Sports',
    description: 'Track-bred aerodynamics and a twin-turbo heart make the Eclipse GT-9 a weapon on any circuit.',
    basePriceINR: 8500000,
    specs: '3.0L Twin-Turbo I6 · 510 HP · 8-Speed DCT',
    image: '/assets/generated/sports-car-01.dim_800x500.png',
  },
  {
    id: 's2',
    name: 'Zenith Striker RS',
    category: 'Sports',
    description: 'Razor-sharp handling and a carbon-fibre chassis deliver a driving experience that borders on telepathic.',
    basePriceINR: 9200000,
    specs: '3.2L Turbo I6 · 540 HP · 7-Speed DCT',
    image: '/assets/generated/sports-car-02.dim_800x500.png',
  },
  {
    id: 's3',
    name: 'Vortex Apex R',
    category: 'Sports',
    description: 'Active aerodynamics and rear-wheel steering make the Apex R the most agile machine in its class.',
    basePriceINR: 11000000,
    specs: '4.0L Twin-Turbo V8 · 620 HP · 8-Speed DCT',
    image: '/assets/generated/sports-car-03.dim_800x500.png',
  },
  {
    id: 's4',
    name: 'Nexara Sprint 450',
    category: 'Sports',
    description: 'Lightweight construction and a naturally aspirated flat-six deliver a pure, unfiltered driving thrill.',
    basePriceINR: 7800000,
    specs: '3.8L NA Flat-6 · 450 HP · 6-Speed Manual',
    image: '/assets/generated/sports-car-04.dim_800x500.png',
  },
  {
    id: 's5',
    name: 'Torqen Blaze S',
    category: 'Sports',
    description: 'A mid-engine layout and bespoke suspension geometry ensure the Blaze S corners like it is on rails.',
    basePriceINR: 10500000,
    specs: '3.5L Twin-Turbo V6 · 580 HP · 7-Speed PDK',
    image: '/assets/generated/sports-car-05.dim_800x500.png',
  },
  {
    id: 's6',
    name: 'Aethon Comet X',
    category: 'Sports',
    description: 'Inspired by endurance racing, the Comet X fuses long-distance comfort with lap-time aggression.',
    basePriceINR: 12500000,
    specs: '4.4L Twin-Turbo V8 · 680 HP · 8-Speed DCT',
    image: '/assets/generated/sports-car-01.dim_800x500.png',
  },
  {
    id: 's7',
    name: 'Luminos Drift Pro',
    category: 'Sports',
    description: 'Rear-wheel drive purity and a limited-slip differential make every corner an invitation to slide.',
    basePriceINR: 6900000,
    specs: '3.0L Turbo I6 · 480 HP · 6-Speed Manual',
    image: '/assets/generated/sports-car-02.dim_800x500.png',
  },
  {
    id: 's8',
    name: 'Ferox Cyclone GT',
    category: 'Sports',
    description: 'A wide-body stance and active exhaust system announce the Cyclone GT before it even arrives.',
    basePriceINR: 9800000,
    specs: '4.0L Turbo V8 · 600 HP · 8-Speed Auto',
    image: '/assets/generated/sports-car-03.dim_800x500.png',
  },
  {
    id: 's9',
    name: 'Stratos Razor 7',
    category: 'Sports',
    description: 'Developed with motorsport DNA, the Razor 7 delivers sub-3-second acceleration with surgical precision.',
    basePriceINR: 14000000,
    specs: '4.4L Twin-Turbo V8 · 720 HP · 8-Speed DCT',
    image: '/assets/generated/sports-car-04.dim_800x500.png',
  },
  {
    id: 's10',
    name: 'Krypton Surge EV',
    category: 'Sports',
    description: 'All-electric performance with instant torque vectoring — the future of sports driving, available today.',
    basePriceINR: 13500000,
    specs: 'Dual Motor EV · 750 HP · Single-Speed',
    image: '/assets/generated/sports-car-05.dim_800x500.png',
  },

  // ── LUXURY ───────────────────────────────────────────────────────────────
  {
    id: 'l1',
    name: 'Imperion Sovereign L',
    category: 'Luxury',
    description: 'Hand-crafted over 400 hours, the Sovereign L wraps its occupants in cashmere, walnut, and silence.',
    basePriceINR: 15000000,
    specs: '4.4L Twin-Turbo V8 · 530 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-01.dim_800x500.png',
  },
  {
    id: 'l2',
    name: 'Celestia Grand Tourer',
    category: 'Luxury',
    description: 'A continent-crossing grand tourer with a 24-speaker audio system and massaging seats for every passenger.',
    basePriceINR: 18500000,
    specs: '6.0L V12 · 600 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-02.dim_800x500.png',
  },
  {
    id: 'l3',
    name: 'Aurum Prestige 760',
    category: 'Luxury',
    description: 'The pinnacle of long-wheelbase luxury — a private sanctuary on wheels with executive rear seating.',
    basePriceINR: 22000000,
    specs: '6.6L Twin-Turbo V12 · 650 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-03.dim_800x500.png',
  },
  {
    id: 'l4',
    name: 'Elysian Phantom SE',
    category: 'Luxury',
    description: 'Starlight headliner, bespoke fragrance diffuser, and a whisper-quiet cabin define the Phantom SE.',
    basePriceINR: 35000000,
    specs: '6.75L Twin-Turbo V12 · 570 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-04.dim_800x500.png',
  },
  {
    id: 'l5',
    name: 'Regalia Opulence X',
    category: 'Luxury',
    description: 'Sculpted from a single aluminium billet, the Opulence X is as much sculpture as it is automobile.',
    basePriceINR: 28000000,
    specs: '5.0L Supercharged V8 · 620 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-05.dim_800x500.png',
  },
  {
    id: 'l6',
    name: 'Noblesse Limousine VII',
    category: 'Luxury',
    description: 'A stretched wheelbase and a partition glass separate the driver from a world of pure indulgence.',
    basePriceINR: 42000000,
    specs: '6.0L V12 · 560 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-06.dim_800x500.png',
  },
  {
    id: 'l7',
    name: 'Velour Serenity 500',
    category: 'Luxury',
    description: 'Adaptive air suspension and active noise cancellation create a ride so smooth it feels like levitation.',
    basePriceINR: 16500000,
    specs: '3.0L Turbo I6 · 490 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-07.dim_800x500.png',
  },
  {
    id: 'l8',
    name: 'Majestica Coupé 12',
    category: 'Luxury',
    description: 'Two-door luxury at its most dramatic — a sweeping roofline and a V12 engine that purrs like thunder.',
    basePriceINR: 32000000,
    specs: '6.0L V12 · 680 HP · 8-Speed DCT',
    image: '/assets/generated/vintage-car-08.dim_800x500.png',
  },
  {
    id: 'l9',
    name: 'Grandioso Touring E',
    category: 'Luxury',
    description: 'Plug-in hybrid technology meets old-world craftsmanship in this electrified luxury estate.',
    basePriceINR: 19000000,
    specs: 'PHEV 3.0L I6 + Motor · 520 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-09.dim_800x500.png',
  },
  {
    id: 'l10',
    name: 'Pinnacle Ultra 900',
    category: 'Luxury',
    description: 'The most exclusive vehicle in the HOOD lineup — built to order, delivered in 18 months, owned by few.',
    basePriceINR: 75000000,
    specs: '6.75L Twin-Turbo V12 · 900 HP · 8-Speed Auto',
    image: '/assets/generated/vintage-car-10.dim_800x500.png',
  },
];

export const vintageModels = carModels.filter((c) => c.category === 'Vintage');
export const sportsModels = carModels.filter((c) => c.category === 'Sports');
export const luxuryModels = carModels.filter((c) => c.category === 'Luxury');
